---
apiVersion: v1
kind: Pod
metadata:
  name: pod-multitool
  labels:
    app: pod-multitool
spec:
  containers:
    - name: multitool
      image: praqma/network-multitool:alpine-extra
      ports:
        - name: "http"
          containerPort: 8082
        - name: "https"
          containerPort: 8444
